all: main.class Inode.class dir.class util.class file.class
main.class: main.java
	javac -d . -classpath . main.java
Inode.class: Inode.java
	javac -d . -classpath . Inode.java
dir.class: dir.java
	javac -d . -classpath . dir.java
util.class: util.java
	javac -d . -classpath . util.java
file.class: file.java
	javac -d . -classpath . file.java